#!/bin/sh
# Builds CezanneGPU.kext (driver/core plus this IOKit adapter) for x86_64 with
# the active Xcode SDK. Builds only: it never loads, installs or signs the kext.
# Usage: driver/kext/build.sh OUTPUT_DIR   (OUTPUT_DIR must not exist yet)
#
# Stage 13 embeds the pinned SDMA firmware, read from ignored out/ (or
# CEZANNE_SDMA_FW) and checked by SHA-256; the generated array stays in
# OUTPUT_DIR, never in Git. See docs/firmware-provenance.md.
# Stage 21 embeds the five pinned GFX files (CE, PFP, ME, MEC, RLC) the same
# way, from the same directory (or CEZANNE_GFX_FW_DIR).
set -eu
[ $# -eq 1 ] || { echo "usage: $0 OUTPUT_DIR" >&2; exit 1; }
out=$1
[ ! -e "$out" ] || { echo "refusing to overwrite $out" >&2; exit 1; }
here=$(cd "$(dirname "$0")" && pwd)
core="$here/../core"
sdk=$(xcrun --sdk macosx --show-sdk-path)
headers="$sdk/System/Library/Frameworks/Kernel.framework/Headers"
kext="$out/CezanneGPU.kext"
mkdir -p "$kext/Contents/MacOS" "$out/obj"
# IOPCIDevice is marked deprecated in favour of PCIDriverKit, which cannot host
# a GPU driver; only that warning is allowed.
common="-arch x86_64 -mmacosx-version-min=26.0 -isysroot $sdk -isystem $headers -nostdinc -mkernel
  -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -Wall -Wextra -Werror
  -Wno-deprecated-declarations -O2"
cxx="-std=c++17 -fapple-kext -fno-rtti -fno-exceptions -fno-builtin -I $core"
xcrun clang $common -std=c11 -c "$here/kmod_info.c" -o "$out/obj/kmod_info.o"
xcrun clang++ $common $cxx -c "$core/cezanne_core.cpp" -o "$out/obj/cezanne_core.o"
xcrun clang++ $common $cxx -c "$here/CezanneGPU.cpp" -o "$out/obj/CezanneGPU.o"
fw=${CEZANNE_SDMA_FW:-$here/../../out/firmware-provenance/fw/green_sardine_sdma.bin}
pin=cba8658ea950a99115ca46ee88c9622240632a0ca1731abbcd18b6d9be9e09de
[ -f "$fw" ] || { echo "missing SDMA firmware $fw (docs/firmware-provenance.md)" >&2; exit 1; }
[ "$(shasum -a 256 "$fw" | cut -d ' ' -f 1)" = "$pin" ] || { echo "SDMA firmware SHA-256 mismatch: $fw" >&2; exit 1; }
{
  echo '#include <stdint.h>'
  echo '// Generated by driver/kext/build.sh from green_sardine_sdma.bin; not tracked.'
  echo 'extern const uint8_t kCezanneSdmaImage[] = {'
  xxd -i < "$fw"
  echo '};'
  echo 'extern const uint32_t kCezanneSdmaImageLength = sizeof(kCezanneSdmaImage);'
} > "$out/obj/sdma_image.cpp"
xcrun clang++ $common $cxx -c "$out/obj/sdma_image.cpp" -o "$out/obj/sdma_image.o"
gfxdir=${CEZANNE_GFX_FW_DIR:-$here/../../out/firmware-provenance/fw}
{
  echo '#include <stdint.h>'
  echo '// Generated by driver/kext/build.sh from the green_sardine GFX files; not tracked.'
  for entry in ce:3bba10cff48ec51eb63e78078456596258c9fea2e8b38d91d02be66c0aca70fd \
               pfp:94e1474b3c8d422e35661d2d584297d891464c173ebf4ad45536277bdf7bdcdc \
               me:671af908c8d631e659895d62db2e6bffc1d2c87d6db4c08246be0216f468fb9c \
               mec:0e4c6712f75af494c3fd70386bc07739cab3aafd77c4fe8efb46c0bc1ae4eba6 \
               rlc:66f4397c2e9d19af245f9da290c8678eb1a51cc815fa7864a9383c2cd0db319d; do
    name=${entry%%:*}
    file="$gfxdir/green_sardine_$name.bin"
    [ -f "$file" ] || { echo "missing GFX firmware $file (docs/firmware-provenance.md)" >&2; exit 1; }
    [ "$(shasum -a 256 "$file" | cut -d ' ' -f 1)" = "${entry#*:}" ] ||
      { echo "GFX firmware SHA-256 mismatch: $file" >&2; exit 1; }
    echo "extern const uint8_t kCezanneGfx_$name[] = {"
    xxd -i < "$file"
    echo '};'
    echo "extern const uint32_t kCezanneGfxLength_$name = sizeof(kCezanneGfx_$name);"
  done
} > "$out/obj/gfx_images.cpp"
xcrun clang++ $common $cxx -c "$out/obj/gfx_images.cpp" -o "$out/obj/gfx_images.o"
xcrun clang++ -arch x86_64 -mmacosx-version-min=26.0 -isysroot "$sdk" -nostdlib -Xlinker -kext \
  -Xlinker -export_dynamic "$out/obj/kmod_info.o" "$out/obj/cezanne_core.o" "$out/obj/CezanneGPU.o" \
  "$out/obj/sdma_image.o" "$out/obj/gfx_images.o" \
  -lkmodc++ -lkmod -lcc_kext -o "$kext/Contents/MacOS/CezanneGPU"
cp "$here/Info.plist" "$kext/Contents/Info.plist"
echo "$kext"
