#!/bin/sh
# Builds CezanneGPU.kext (driver/core plus this IOKit adapter) for x86_64 with
# the active Xcode SDK. Builds only: it never loads, installs or signs the kext.
# Usage: driver/kext/build.sh OUTPUT_DIR   (OUTPUT_DIR must not exist yet)
#
# Stage 13 embeds the pinned SDMA firmware, read from ignored out/ (or
# CEZANNE_SDMA_FW) and checked by SHA-256; the generated array stays in
# OUTPUT_DIR, never in Git. See docs/firmware-provenance.md.
set -eu
[ $# -eq 1 ] || { echo "usage: $0 OUTPUT_DIR" >&2; exit 1; }
out=$1
[ ! -e "$out" ] || { echo "refusing to overwrite $out" >&2; exit 1; }
here=$(cd "$(dirname "$0")" && pwd)
core="$here/../core"
sdk=$(xcrun --sdk macosx --show-sdk-path)
headers="$sdk/System/Library/Frameworks/Kernel.framework/Headers"
kext="$out/CezanneGPU.kext"
mkdir -p "$kext/Contents/MacOS" "$out/obj"
# IOPCIDevice is marked deprecated in favour of PCIDriverKit, which cannot host
# a GPU driver; only that warning is allowed.
common="-arch x86_64 -mmacosx-version-min=26.0 -isysroot $sdk -isystem $headers -nostdinc -mkernel
  -DKERNEL -DKERNEL_PRIVATE -DDRIVER_PRIVATE -DAPPLE -DNeXT -Wall -Wextra -Werror
  -Wno-deprecated-declarations -O2"
cxx="-std=c++17 -fapple-kext -fno-rtti -fno-exceptions -fno-builtin -I $core"
xcrun clang $common -std=c11 -c "$here/kmod_info.c" -o "$out/obj/kmod_info.o"
xcrun clang++ $common $cxx -c "$core/cezanne_core.cpp" -o "$out/obj/cezanne_core.o"
xcrun clang++ $common $cxx -c "$here/CezanneGPU.cpp" -o "$out/obj/CezanneGPU.o"
fw=${CEZANNE_SDMA_FW:-$here/../../out/firmware-provenance/fw/green_sardine_sdma.bin}
pin=cba8658ea950a99115ca46ee88c9622240632a0ca1731abbcd18b6d9be9e09de
[ -f "$fw" ] || { echo "missing SDMA firmware $fw (docs/firmware-provenance.md)" >&2; exit 1; }
[ "$(shasum -a 256 "$fw" | cut -d ' ' -f 1)" = "$pin" ] || { echo "SDMA firmware SHA-256 mismatch: $fw" >&2; exit 1; }
{
  echo '#include <stdint.h>'
  echo '// Generated by driver/kext/build.sh from green_sardine_sdma.bin; not tracked.'
  echo 'extern const uint8_t kCezanneSdmaImage[] = {'
  xxd -i < "$fw"
  echo '};'
  echo 'extern const uint32_t kCezanneSdmaImageLength = sizeof(kCezanneSdmaImage);'
} > "$out/obj/sdma_image.cpp"
xcrun clang++ $common $cxx -c "$out/obj/sdma_image.cpp" -o "$out/obj/sdma_image.o"
xcrun clang++ -arch x86_64 -mmacosx-version-min=26.0 -isysroot "$sdk" -nostdlib -Xlinker -kext \
  -Xlinker -export_dynamic "$out/obj/kmod_info.o" "$out/obj/cezanne_core.o" "$out/obj/CezanneGPU.o" \
  "$out/obj/sdma_image.o" \
  -lkmodc++ -lkmod -lcc_kext -o "$kext/Contents/MacOS/CezanneGPU"
cp "$here/Info.plist" "$kext/Contents/Info.plist"
echo "$kext"
